services:
  ros2:
    build:
      context: ./src/robot
      dockerfile: Dockerfile
    container_name: ros2_bridge
    ports:
      - "9090:9090"
    environment:
      - ROS_DOMAIN_ID=0
      - TZ=Asia/Tokyo
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: vla_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      # prevent overwriting container's node_modules with local empty folder
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_ROSBRIDGE_URL=ws://localhost:9090
      - VITE_BACKEND_URL=http://localhost:8000
      - TZ=Asia/Tokyo
    depends_on:
      - ros2
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: vla_backend
    ports:
      - "8000:8000"
    environment:
      - SAVE_DEBUG_IMAGES=true
      - TZ=Asia/Tokyo
    volumes:
      - ./src/backend:/app
      - ./src/backend/debug_images:/app/debug_images
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    restart: unless-stopped
